### ISSUE TITLE
[Bug Report] PlayerStatisticLoaderFromFile ignores level-name

### ISSUE THREAD

**Issue by drkn** [sladkoff/minecraft-prometheus-exporter#117]
PlayerStatisticLoaderFromFile has hardcoded "level-name" as "world". If you change level-name - the plugin fails to start with java.nio.file.NoSuchFileException: /data/world/stats . World name should be read from server.properties or configured in plugin config.

**Comment by MarvinKlar** [comment]
I fixed this: https://github.com/sladkoff/minecraft-prometheus-exporter/pull/121
