### ISSUE TITLE
 Where can I find the prometheus-exporter.jar file?

### ISSUE THREAD

**Issue by lorenzocomotti** [sladkoff/minecraft-prometheus-exporter#12]
Hi,
In the guide, you say to copy the file prometheus-exporter.jar into the Plugin folder. Where can I find or create the mentioned file?

Thank you
Lorenzo

**Comment by sladkoff** [comment]
Hi! You can find the latest jar on the [releases](https://github.com/sladkoff/minecraft-prometheus-exporter/releases) page.

Cheers
