### ISSUE TITLE
[Bug Report] Connection Refused

### ISSUE THREAD

**Issue by eruizc-dev** [sladkoff/minecraft-prometheus-exporter#123]
When querying from outside `localhost` the server does not respond:

![image](https://user-images.githubusercontent.com/58179604/145860797-7a51c9b5-0ef2-49c4-8cb4-65240b58e54a.png)

I run Minecraft, Prometheus, and Grafana in separate docker containers. I have other monitors working fine but this one doesn't want to respond outside localhost, as you can see:

![image](https://user-images.githubusercontent.com/58179604/145861647-37a2f972-b5b9-47a8-91f1-5388ce9f7945.png)

I think I found the source of the issue: in [this line](https://github.com/sladkoff/minecraft-prometheus-exporter/blob/master/src/main/java/de/sldk/mc/PrometheusExporter.java#L24-L27
) the server is initialized with a hardcoded HOST of `localhost`. Maybe it should be initialized with null or using a different constructor.

- [x] I have successfully configured Prometheus
- [x] I have successfully configured Grafana
- [x] I have added a **valid** scrape config for my Minecraft server in Prometheus
- [x] I know how to build Grafana dashboards and Prometheus queries

**Comment by eruizc-dev** [comment]
If you're interested, I can try fix this during the week

**Comment by sladkoff** [comment]
@eruizc-dev You can configure the `host` setting in the plugin config as seen [here](https://github.com/sladkoff/minecraft-prometheus-exporter#plugin-config). 

In your case, use this:

```yml
host: 0.0.0.0
```

**Comment by eruizc-dev** [comment]
I'm such an idiot, it's the first line in the documentation (set host to 0.0.0.0 in config.yml).

Shouldn't 0.0.0.0 be the default tho?

**Comment by eruizc-dev** [comment]
@sladkoff yeah thanks, I completely missed that lo

**Comment by sladkoff** [comment]
> Shouldn't 0.0.0.0 be the default tho?

@eruizc-dev The current idea is that it's private by default and you need to opt-in to expose it / make it public.

**Comment by eruizc-dev** [comment]
Fair enough
