### ISSUE TITLE
[Question] Does it work with 1.18?

### ISSUE THREAD

**Issue by TimyIsCool** [sladkoff/minecraft-prometheus-exporter#126]
Hey I was wonder if It works with 1.18 so I can use it on my server

**Comment by badrpc** [comment]
I'm using it with PaperMC (papermc.io) 1.18.1 (and briefely with 1.18) and I haven't noticed any issues.

**Comment by eruizc-dev** [comment]
Yes, I've been using it for a week with no issues.

**Comment by ItsRainingHP** [comment]
Confirmed been using it for a week as well on MC 1.18 Paper.

**Comment by sladkoff** [comment]
Question has been answered :)
