### ISSUE TITLE
[Feature Request] Track Admin/OP Accounts

### ISSUE THREAD

**Issue by ItsRainingHP** [sladkoff/minecraft-prometheus-exporter#129]
**Is your feature request related to a problem? Please describe.**
This is related to players online metric. It would be nice to be able to subtract admin/OP accounts from the players online panel.

**Describe the solution you'd like**
A metric to track admin/OP accounts

**Describe alternatives you've considered**
Subtracting admin accounts or excluding them from the metric.

**Comment by eruizc-dev** [comment]
Rather than subtracting operators, I'd rather have a label. Will provide way more flexibility.

`privileges=player` or `privileges=operator` would be nice and flexible in case plugins add other types of privileges

**Comment by eruizc-dev** [comment]
@sladkoff

I'm interested in coding this. Could you help me with the specs?

Currently, the `player_online` metric has name and uuid as labels with 0/1 label depending if it's online or not. Should more labels be added or a new metric be created?

**Comment by sladkoff** [comment]
@eruizc-dev Without having put too much thought into this, I'd probably just add a new label to the existing metric. It kinda fits with the existing labels that identify the player. What do you think?
