### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Jcodeerd** [sladkoff/minecraft-prometheus-exporter#165]
Players cant connect/join after adding the plugin; https://img.foxhideout.com/MDWvD.png

# Plugins (after removing PrometheusExporter):
```  ajQueue, AuthMe, BungeeGuard, Citizens, DecentHolograms, DeluxeHub, FastLogin, LPC, LuckPerms, Multiverse-Core, PlaceholderAPI, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard```

**Comment by sladkoff** [comment]
Can you provide any more context? The logs of the Prometheus exporter plugin would be helpful.

**Comment by Jcodeerd** [comment]
https://mcpaste.io/86838040d07c4e8d It basically just stops the server, such as /pl not working, /tps etc

**Comment by Jcodeerd** [comment]
Im using java 11

**Comment by Jcodeerd** [comment]
@sladkoff  :)

**Comment by sladkoff** [comment]
@Jcodeerd Do you happen to have a huge map?

**Comment by Jcodeerd** [comment]
Yes, it also happens on both large and small maps.
