### ISSUE TITLE
[Question] Cannot find prometheus-exporter.jar file

### ISSUE THREAD

**Issue by lslamp** [sladkoff/minecraft-prometheus-exporter#168]
- [x] I have successfully configured Prometheus - 
This is done
- [x] I have successfully configured Grafana - 
This is done
- [ ] I have added a **valid** scrape config for my Minecraft server in Prometheus -- 
This is the part I cannot figure. The instructions say drop the .jar file into the plugin dir, but after downloading the code, I cannot find the prometheus-exporter.jar to drop into the plugins dir. Do I have to compile the file myself, if so how? 
- [ ] I know how to build Grafana dashboards and Prometheus queries -- Using the dashboard I imported.

Where can I download the prometheus-exporter.jar file?

Thanks
Lawrence

**Comment by badrpc** [comment]
Releases section?

https://github.com/sladkoff/minecraft-prometheus-exporter/releases

**Comment by lslamp** [comment]
@badrpc you are a star, thanks for the direction.
Lawrence
