### ISSUE TITLE
Failed to read player statistic: Label cannot be null.

### ISSUE THREAD

**Issue by jc0b** [sladkoff/minecraft-prometheus-exporter#17]
Hi,

I'm running PaperMC 1.14.1 (build #32), and I keep getting the above error. None of the individual statistics seem to be appearing in Prometheus, but I haven't been able to figure out why I'm getting the above error. I have individual player statistics enabled, and in the server logs the exporter confirms this by printing the warning to the console. Any ideas?

![Screenshot 2019-05-20 at 20 52 32](https://user-images.githubusercontent.com/27809638/58044931-5c1ce900-7b41-11e9-9e8f-fc6314da735c.png)

**Comment by sladkoff** [comment]
Hi @jc0b,

Thanks for the report. I don't use PaperMC and haven't tested it. Might be something specific to that platform?

I'll take a look.

**Comment by jc0b** [comment]
Thanks @sladkoff! I'm fairly new to paper, but I believe it's a fork of Bukkit, so it should be fairly similar to that. Thanks for taking a look!

**Comment by sladkoff** [comment]
@jc0b If you're still using this, could you test the [latest version](https://github.com/sladkoff/minecraft-prometheus-exporter/releases/tag/v2.0.0) of the plugin and report if this is still happening?

**Comment by jc0b** [comment]
Hi,
I’ll be putting this back into production in about a month, I’ll let you know then. Might be worth marking this issue as closed until I can test it.


On 30 Dec 2019, at 12:30, Leonid <notifications@github.com> wrote:

﻿

@jc0b<https://github.com/jc0b> If you're still using this, could you test the latest version<https://github.com/sladkoff/minecraft-prometheus-exporter/releases/tag/v2.0.0> of the plugin and report if this is still happening?

**Comment by sladkoff** [comment]
@ShadowFM Can you provide some additional information about your server (are you using Bukkit / Spigot / PaperMC)? Thanks.

**Comment by ShadowFM** [comment]
Sure.
I'm using:
CraftBukkit: git-Spigot-3b314f5-e2790ae (MC: 1.15) (Implementing API version 1.15-R0.1-SNAPSHOT)
minecraft-prometheus-exporter: 2.0.0
