### ISSUE TITLE
Trying to get maximal player count

### ISSUE THREAD

**Issue by DotDebian** [sladkoff/minecraft-prometheus-exporter#18]
Hello, I would like to add a panel for the maximal online player count. I tried `max(mc_players_total{state="online"})` but it's not working; it's displaying players :(

How can I do this?

**Comment by sladkoff** [comment]
Hi,

I think you may be looking for `max_over_time(mc_players_total{state="online"}[1d])`. That will give you the players per day. Play around with the range-vector and set it to something high like `5y` if you want the max over "all time".

Hope this helps.
