### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Elzorro99** [sladkoff/minecraft-prometheus-exporter#19]
Hello, sladkoff.

Please, Can you give me the APIs you use in Decompile.

PS: Sorry for the spelling I'm french ;)

Thank you good day.

**Comment by sladkoff** [comment]
Hi!

I'm sorry, I don't understand. You can just import the project as Maven Project in IntelliJ or Eclipse and all dependencies should be available, no?

**Comment by Elzorro99** [comment]
![image](https://user-images.githubusercontent.com/38183701/59200168-ea601a00-8b97-11e9-8af2-dd607ee3b719.png)

Can you give me that :) Please

**Comment by Elzorro99** [comment]
For information: I use jdk 8

**Comment by Elzorro99** [comment]
I do not use Maven.

**Comment by sladkoff** [comment]
That's a shame because this is a Maven project.

Look [in the pom.xml](https://github.com/sladkoff/minecraft-prometheus-exporter/blob/7038f4e801e440d8ff7f03fdc206527c42254c83/pom.xml#L38-L47).

Then use https://search.maven.org/ with the groupId + artifactId from the above step to find the jars.
