### ISSUE TITLE
[Bug Report] [PrometheusExporter] Failed to read server statistic: null

### ISSUE THREAD

**Issue by MarvinKlar** [sladkoff/minecraft-prometheus-exporter#200]
I am using Plugin version: 2.5.0
Paper Version: git-Paper-84 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5059ada)

On server shutdown, the plugins most likely prints the error `[PrometheusExporter] Failed to read server statistic: null`. Why is that so? Please remove that error. Thanks!

**Comment by MarvinKlar** [comment]
@sladkoff is there a way to fix this?

**Comment by sladkoff** [comment]
It's just logging a warning because the server is shutting down and metrics can no longer be collected at that time. I can see if I can tweak the logging but this is not an error in the plugin.

**Comment by MarvinKlar** [comment]
It just catches my eye every time i viee the logs. Would it be helpful if I try to work around this stacktrace with a PR?
