### ISSUE TITLE
How to show players online per dimension?

### ISSUE THREAD

**Issue by lukeeexd** [sladkoff/minecraft-prometheus-exporter#21]
Like this https://i.imgur.com/T1z3AtG.png

Currently my graph is just players online, how can I show players online in world, world_nether and world_the_end?

**Comment by sladkoff** [comment]
Did you try the `mc_players_online_total` metric?

**Comment by lukeeexd** [comment]
Yes it just shows all online players in every dimension not online players per dimension like the above screenshot

**Comment by sladkoff** [comment]
There's `mc_players_total` and `mc_players_online_total`. Are you sure that you aren't using the first of the two?

**Comment by lukeeexd** [comment]
Okay that worked. How do I make it display the world name in the legend ? And not just “state”?

**Comment by sladkoff** [comment]
Change the legend format to `{{world}}`.
