### ISSUE TITLE
Prometheus keeps crashing when i add the minecraft Job

### ISSUE THREAD

**Issue by toastydoctor** [sladkoff/minecraft-prometheus-exporter#27]
# Read before opening a question!

First, please ensure that you have done the following things on your own.

- [x] I have successfully configured Prometheus
- [x] I have successfully configured Grafana
- [ ] I have added a **valid** scrape config for my Minecraft server in Prometheus
- [x] I know how to build Grafana dashboards and Prometheus queries

These steps are out of the scope of this issue tracker. If you have questions about any of these steps, please refer to the respective documentations:

- [Prometheus Docs](https://prometheus.io/docs/prometheus/latest/getting_started/)
- [Prometheus Docs - Querying Basics](https://prometheus.io/docs/prometheus/latest/querying/basics/#querying-prometheus)
- [Grafana Docs](https://grafana.com/docs/grafana/latest/features/datasources/prometheus/)

**Comment by sladkoff** [comment]
Hm, I don't think I can help you. You haven't added any description and if "Prometheus is crashing" then it isn't an issue with this plugin. Please refer to https://prometheus.io/docs/prometheus/latest/getting_started/ for more information on how to configure the scrape target.

You can verify that the exporter works by going to `http://your-server-hostname:9225/metrics` in a browser. Then set up your Prometheus to reach that URL.

**Comment by toastydoctor** [comment]
ok well the exporter doesent seem to work for me when i visit my-mcserver-ip:9225/metrics the site wont load i just get "This site can’t be reached
                                  192.168.2.122 refused to connect."

**Comment by sladkoff** [comment]
@toastydoctor Any errors in the logs? Is your running on the same host as the MC server? If not, then you will have to set the `host` in the config.yml to something other than `localhost` depending on your setup. 

You will have to set `host: localhost`

**Comment by toastydoctor** [comment]
where are the logs i only have the config.yml in the prometheus exporter folder

**Comment by toastydoctor** [comment]
ok so the minecraft logs tell me that :[PrometheusExporter] Started Prometheus metrics endpoint at: localhost:9225

**Comment by sladkoff** [comment]
Can you try with this in the plugin config.yml: `host: 192.168.2.122`

**Comment by toastydoctor** [comment]
nope still : This site can’t be reached

**Comment by toastydoctor** [comment]
ok nevermind it works now 

Thx so much for taking ur time

**Comment by AlexUtzl67** [comment]
Hello, I'm also stuck on the same subject. Could you tell me how did you succeed.
