### ISSUE TITLE
Host configuration suggestion

### ISSUE THREAD

**Issue by gabrielsson** [sladkoff/minecraft-prometheus-exporter#34]
Great repo! I got everything up and running on my raspberry pi kubernetes cluster. Pretty cool. 

One thing that took some time to figure out was the config.yaml configuration for host. As I run this in kubernetes I have no way of knowing before hand what IP or Host I am getting so I had to read up on the Jetty configuration for starting the server. Turns out that if I set it to 0.0.0.0 I can have promtheus scrape the endpoint succesfully, but with localhost it is not getting through. 

A suggestion would be to change the default of localhost to 0.0.0.0 as that will be more permissive for anyone running the plugin. If not, maybe add an entry under quickstart that using 0.0.0.0 will be ideal when running minecraft containerized.

**Comment by sladkoff** [comment]
The default is fine because we don't want to 'expose' too much by default. You can always opt-in to have it listen on all interfaces if you know what you're doing.

I updated the README with a sample config and added a note about Kubernetes to make this easier.

Thanks for the feedback!
