### ISSUE TITLE
[Feature Request] Support of JVM metrics like micrometer

### ISSUE THREAD

**Issue by lightsing** [sladkoff/minecraft-prometheus-exporter#35]
**Is your feature request related to a problem? Please describe.**
Although now it has a  JVM of memeory usage, I'd like to inspect more details like the gc event, thread pool, class loader which could help to find out how to imporve the performance.

**Describe the solution you'd like**
Build in the [micrometer](https://micrometer.io/) lib and proxy its metrics result.

**Describe alternatives you've considered**
Might it not complex and you can do it without micrometer.

**Comment by sladkoff** [comment]
Good idea! The micrometer implementation should be a good way to go. This is up for grabs.
