### ISSUE TITLE
[Question] Player online is just a flat line

### ISSUE THREAD

**Issue by lukeeexd** [sladkoff/minecraft-prometheus-exporter#43]
# Read before opening a question!

First, please ensure that you have done the following things on your own.

- [* ] I have successfully configured Prometheus
- [* ] I have successfully configured Grafana
- [* ] I have added a **valid** scrape config for my Minecraft server in Prometheus
- [* ] I know how to build Grafana dashboards and Prometheus queries

https://i.tws.gg/jOeKyVw1la.png How do I make them like https://i.tws.gg/0UYqpOf7qo.png ?

**Comment by sladkoff** [comment]
Is that the only flat line? Do the other metrics work?

**Comment by lukeeexd** [comment]
> Is that the only flat line? Do the other metrics work?

Nope thats the only one, When I hide this https://i.tws.gg/fMR6L4griS.png it shows fine, although kinda smushed https://i.tws.gg/vuVbj6Pkn1.png

**Comment by sladkoff** [comment]
I see. It's just that `mc_players_total` is really high relative to your online players.

You could try and play around with the Y axis scale:

![image](https://user-images.githubusercontent.com/6025787/82130806-0bc97d00-97cf-11ea-9d47-563a48be0a09.png)

If it still feels smushed to you, you can always customize the dashboard to your liking.
