### ISSUE TITLE
Tick times per entity

### ISSUE THREAD

**Issue by lukeeexd** [sladkoff/minecraft-prometheus-exporter#44]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Having the tick times for different entites would be nice. e.g villagers, hoppers, furnaces, zombies etc 

**Describe alternatives you've considered**

**Additional context**
I'll add a screenshot of what I mean when I can find it again

**Comment by sladkoff** [comment]
I don't think that this is possible. The current tick times are taken directly from the server implementations and we don't have any entity information at that point. The server would have to provide this information.

@Combustible Do you agree?

**Comment by lukeeexd** [comment]
Its definitely possible as I've seen somebody have it. I'll ask for a screenshot off them since I cant find it anymore.

**Comment by lukeeexd** [comment]
https://cdn.discordapp.com/attachments/538139695079489587/701843317020950568/unknown.png This isnt it, but maybe you could get some ideas off this? Still looking for what I'm talking about

**Comment by lukeeexd** [comment]
https://cdn.discordapp.com/attachments/538139695079489587/697498779464499236/analytics.png Okay maybe it was this I was thinking of but interpreted it wrongly

**Comment by fishzle** [comment]
@lukeeexd do you mean something like the second dashboard shown here: https://grafana.com/grafana/dashboards/11993
