### ISSUE TITLE
[Bug Report] Unknown panel type: gauge

### ISSUE THREAD

**Issue by Marcuri02** [sladkoff/minecraft-prometheus-exporter#45]
# Read before opening a bug report!

First, please ensure that you have done the following things on your own.

- [x] I have successfully configured Prometheus
- [x] I have successfully configured Grafana
- [x] I have added a **valid** scrape config for my Minecraft server in Prometheus
- [ ] I know how to build Grafana dashboards and Prometheus queries

These steps are out of the scope of this issue tracker. If you have problems with any of these steps, please refer to the respective documentations:

- [Prometheus Docs](https://prometheus.io/docs/prometheus/latest/getting_started/)
- [Prometheus Docs - Querying Basics](https://prometheus.io/docs/prometheus/latest/querying/basics/#querying-prometheus)
- [Grafana Docs](https://grafana.com/docs/grafana/latest/features/datasources/prometheus/)

![image](https://user-images.githubusercontent.com/13281890/83328691-37476f80-a285-11ea-80db-16360e3d0104.png)

Gauge module not working.

**Comment by sladkoff** [comment]
Which version of Grafana? Can you use gauge panels on other dashboards?

**Comment by sladkoff** [comment]
Stale.
