### ISSUE TITLE
[Bug Report] Entities counter is inaccurate

### ISSUE THREAD

**Issue by Govindass** [sladkoff/minecraft-prometheus-exporter#46]
# Read before opening a bug report!

First, please ensure that you have done the following things on your own.

- [V ] I have successfully configured Prometheus
- [V] I have successfully configured Grafana
- [V] I have added a **valid** scrape config for my Minecraft server in Prometheus
- [kinda] I know how to build Grafana dashboards and Prometheus queries

I've found a bug that if all entities disappear from a world, it does not update their counter on grafana, they keep being for example "14" instead of going to 0 (pretty much it never reaches 0) I'm not sure if it's a configuration issue on my side or a bug in the plugin

**Comment by sladkoff** [comment]
How do you measure that "all entities disappear from a world"? We're currently just exporting whatever entity count the server implementation gives us, so there's probably not much we can change.

**Comment by Govindass** [comment]
> 
> 
> How do you measure that "all entities disappear from a world"? We're currently just exporting whatever entity count the server implementation gives us, so there's probably not much we can change.

I mean, when all entities get unloaded, like all chunks unload, so all entities unload too

so there are 0 chunks and 0 entities in the world

the chunks counter is right, it shows 0

but entity counter remains showing entity counts before the chunk unloading, while there really aren't any entities (checking with separate plugin)

**Comment by Govindass** [comment]
the solution would be to save counts in a variable and if no entities of that type that was sent earlier appear, then send 0

**Comment by Govindass** [comment]
I think player count counter is also having a similar problem, it says 12 players online while only 3 are online and there haven't been 12 online for a long time

**Comment by Govindass** [comment]
chunks loaded seem to also get wrong if the world gets unloaded

**Comment by schoentoon** [comment]
Would it not simply be a matter of clearing out `ENTITIES` in https://github.com/sladkoff/minecraft-prometheus-exporter/blob/master/src/main/java/de/sldk/mc/metrics/Entities.java before iterating over all the worlds in https://github.com/sladkoff/minecraft-prometheus-exporter/blob/master/src/main/java/de/sldk/mc/metrics/WorldMetric.java#L17 using the `clear()` method in prometheus?
