### ISSUE TITLE
[Bug Report] My players online is weird

### ISSUE THREAD

**Issue by lukeeexd** [sladkoff/minecraft-prometheus-exporter#47]
# Read before opening a bug report!

First, please ensure that you have done the following things on your own.

- [* ] I have successfully configured Prometheus
- [* ] I have successfully configured Grafana
- [* ] I have added a **valid** scrape config for my Minecraft server in Prometheus
- [* ] I know how to build Grafana dashboards and Prometheus queries

These steps are out of the scope of this issue tracker. If you have problems with any of these steps, please refer to the respective documentations:

The nether is following the world even though theres sometimes 0 people in it

https://i.imgur.com/274KtWG.png

**Comment by sladkoff** [comment]
The graphs are stacked. You can turn that off in the visualization options of the panel.
