### ISSUE TITLE
feature request add used memory as well as free and max

### ISSUE THREAD

**Issue by dezil** [sladkoff/minecraft-prometheus-exporter#5]
I prefer to see my data showing used not free

Cheers

**Comment by sladkoff** [comment]
Me too! Thankfully we have [operators](https://prometheus.io/docs/querying/operators/) in Prometheus queries.

Free memory: `mc_jvm_memory{type='max'} - scalar(mc_jvm_memory{type='free'})`

**Comment by jbhannah** [comment]
Time-traveling from the future to say that `scalar()` didn't work for me, but this did:

```
mc_jvm_memory{type='max'} - ignoring(type) mc_jvm_memory{type='free'}
```
