### ISSUE TITLE
jar file

### ISSUE THREAD

**Issue by SMLMG** [sladkoff/minecraft-prometheus-exporter#50]
# Read before opening a question!
I cloned your repo and read your instructions for use. It starts with the jar file. However, after cloning the repo I cannot find a jar file anywhere. I am running minecraft in a k3 pod on a rpi 4b 8GB running a beta version of the 64 bit Pi OS.  What could go wrong? Possibly I am trying to use this repo on an unsupported platform or in an unsupported manner?  Thank you in advance for any attention.

First, please ensure that you have done the following things on your own.

- [ ] I have successfully configured Prometheus
- [ ] I have successfully configured Grafana
- [ ] I have added a **valid** scrape config for my Minecraft server in Prometheus
- [ ] I know how to build Grafana dashboards and Prometheus queries

These steps are out of the scope of this issue tracker. If you have questions about any of these steps, please refer to the respective documentations:

- [Prometheus Docs](https://prometheus.io/docs/prometheus/latest/getting_started/)
- [Prometheus Docs - Querying Basics](https://prometheus.io/docs/prometheus/latest/querying/basics/#querying-prometheus)
- [Grafana Docs](https://grafana.com/docs/grafana/latest/features/datasources/prometheus/)

**Comment by sladkoff** [comment]
You don't need to clone the repo, you can just download the latest jar from [Releases](https://github.com/sladkoff/minecraft-prometheus-exporter/releases/tag/v2.2.0).

If you want to build from source, do `mvn clean package` in the cloned working directory.

**Comment by SMLMG** [comment]
Thank you so much. Stay safe over there and whatever you see us do you do the opposite.
