### ISSUE TITLE
[Question] Datapack?

### ISSUE THREAD

**Issue by geogdog** [sladkoff/minecraft-prometheus-exporter#55]
I don’t know enough about the internals of plugins vs datapacks, but do you know if this would be possible on a vanilla server in datapack form?

**Comment by sladkoff** [comment]
I don't know much about datapacks but it seems like the scripting capabilities are rather limited to in-game [mcfunctions](https://minecraft.gamepedia.com/Function_(Java_Edition)) and asset mods. We would need to somehow serve an HTTP endpoint and I doubt that this is possible with the integrated functions.
