### ISSUE TITLE
[Feature Request] Have metric about count of each Entity

### ISSUE THREAD

**Issue by madimadi** [sladkoff/minecraft-prometheus-exporter#57]
Hi,
Since the number of entities contribute at some extend to the load of the server it would be very nice to have data for all entities. 

I imaging creating a new graph on dashboard besides the current "Entities" which has details about entity fluctuation over time.
I have a server where various entities are disabled or restriced (worldguard) .

Thanks,
 /madi/

**Comment by sladkoff** [comment]
@madimadi As far as I remember this should already be possible with the `mc_entities_total` metric because it has a `type` label that you can use. 

It might not be included in the sample dashboard but you can do this with your own query.

**Comment by madimadi** [comment]
> @madimadi As far as I remember this should already be possible with the `mc_entities_total` metric because it has a `type` label that you can use.
> 
> It might not be included in the sample dashboard but you can do this with your own query.

You are right. I realized that  it is doable just the matter of modifying the dashboard accordingly.  Thanks for the answer.
