### ISSUE TITLE
[Feature Request] Forge / Sponge support

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [sladkoff/minecraft-prometheus-exporter#58]
I would like to have this plugin as a server side mod for forge server owners or just forge core server, or as a sponge plugin because sponge exists :)

**Describe alternatives you've considered**
I think there is no alternatives i think, i've done very little reserch so i don't realy know if anything exists

**Comment by baer95** [comment]
There is a fork of this repository that implements Sponge support: https://github.com/Stonebound/PrometheusExporter.
It looks like there is not much maintenance going on. Possibly there are other forks that implement support for Forge, but I have not checked.

**Comment by TomAvecLeVdsl** [comment]
Ok thanks for taking the time to respond :)
