### ISSUE TITLE
Configuration help request

### ISSUE THREAD

**Issue by SlimeDog** [sladkoff/minecraft-prometheus-exporter#7]
CentOS 7.3 latest
Spigot 1.11.2 latest
PrometheusExporter 1.1.0
Prometheus 1.6.1
Grafana 4.2.0

Everything is installed and running. Grafana dashboard widgets claim "Datasource named Prometheus was not found". Obviously, I have misconfigured the data stream, but I cannot see how. Any help deeply appreciated.

Grafana Datasource config:
```
Name: BlackDog
Type: Prometheus
Url: http://blackdog.straight8.com:9090
Access: direct
No auth
```
[Save & Test] returns _Success. Datasource is working_

Grafana Dashboards config:
```
Prometheus Stats revision 1 (Imported: 1)
```

PrometheusExporter/config.yml
```port: 9090```

Prometheus/prometheus.yml (business bits)
```scrape_configs:
  - job_name: 'minecraft'
    static_configs:
      - targets: ['localhost:9090']
```

Grafana/grafana.ini: all default values

**Comment by sladkoff** [comment]
@SlimeDog Do your MC server and Prometheus instance run on the same host?

**Comment by SlimeDog** [comment]
Yes. Same host.

**Comment by sladkoff** [comment]
@SlimeDog Try this:

In your **PrometheusExporter/config.yml**:
Change `port: 9090` to anything else or use the default (9225) if you have nothing conflicting with it.
Port 9090 is the default port of the Prometheus server itself. The exporter needs to run on another port (e.g. 9225).

Then update your **Prometheus/prometheus.yml**:
```yml
- job_name: 'minecraft'
    static_configs:
      - targets: ['localhost:9225'] # This port must match the one in the plugin's config.yml!
```

The basic idea behind all of this: 
```
├── Prometheus Exporter plugin exports the latest mc server stats on port 9225
     ├── Prometheus scrapes port 9225 periodically and saves results to database
     └── Prometheus exposes its database on port 9090
          └── Grafana reads raw data from Prometheus port 9090 and displays it as graphs etc.
```
I'd recommend reading the Prometheus/Grafana manuals if you want to learn more.

**Comment by SlimeDog** [comment]
That was my original configuration (I tend to use defaults unless there is a good reason not to do). When it didn't work, I cleverly misunderstood the data flows and configured 9090.

It is now reverted to 9225, as you suggest, and both Prometheus and Spigot restarted. Unfortunately, still no joy. Prometheus says:
```
INFO[0000] Starting prometheus (version=1.6.1, branch=master, revision=4666df502c0e239ed4aa1d80abbbfb54f61b23c3)  source=main.go:88
INFO[0000] Build context (go=go1.8.1, user=root@ca1b452514b7, date=20170419-13:26:24)  source=main.go:89
INFO[0000] Loading configuration file /home/ram/prometheus-1.6.1.linux-amd64/prometheus.yml  source=main.go:251
INFO[0000] Loading series map and head chunks...         source=storage.go:421
INFO[0000] 633 series loaded.                            source=storage.go:432
INFO[0000] Listening on :9090                            source=web.go:259
INFO[0000] Starting target manager...                    source=targetmanager.go:61
```
Does this look correct? Anything else I can check. I see no error messages in either log.

**Comment by sladkoff** [comment]
You could check if Prometheus is scraping the exporter:
Go to http://localhost:9090/targets in your browser and verify that the minecraft endpoint is listed there and the state is up.

If it's up, you can also run some queries (enter `mc_jvm_memory` and click "execute") at http://localhost:9090/graph

If you get results, the Prometheus part is properly configured and you'll need to verify that Grafana can communicate with Prometheus.

**Comment by SlimeDog** [comment]
Thanks. The results  of those steps indicate that Prometheus is properly configured.
```
minecraft
Endpoint: http://localhost:9225/metrics
State: UP
Labels: instance="localhost:9225"
Last Scrape: 19.64s ago
Error:
```
```
mc_jvm_memory{instance="localhost:9225",job="minecraft",type="max"}	7635730432
mc_jvm_memory{instance="localhost:9225",job="minecraft",type="free"}	1117096520
```
So I need to figure out why Grafana is not communicating with Prometheus. Much obliged for the guidance.

**Comment by sladkoff** [comment]
> [Save & Test] returns Success. Datasource is working

You said that the Datasource error only occurs when inside the imported dashboard?

Try to edit one of the panels in said dashboard, go to the 'Metrics' tab and check the 'Panel data source'. Select yours if available. The exemplary `minecraft-grafana.json` dashboard uses a datasource named 'Prometheus' by default. If you named yours differently, this might be the cause. Just update to the datasource in each panel to the correct one.

**Comment by SlimeDog** [comment]
Oh, jeez! That was simple. All better now. Thanks again.

**Comment by sladkoff** [comment]
Yeah, you even mentioned the differing name in the first comment. I should have noticed then :s

**Comment by SlimeDog** [comment]
No worries. It all sorted.
